### ISSUE TITLE
scalikejdbc-play-dbplugin-adapter 2.3.5 doesn't work with ScalikeJDBC 2.2.4

### ISSUE THREAD

**Issue by tsuyoshizawa** [scalikejdbc/scalikejdbc-play-support#14]
```
play.api.UnexpectedException: Unexpected exception[NoSuchMethodError: scalikejdbc.DataSourceConnectionPool.<init>(Ljavax/sql/DataSource;)V]
  at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
  at scala.Option.map(Option.scala:146) ~[scala-library-2.11.5.jar:na]
  at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
  at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.5.jar:na]
  at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.8.jar:2.3.8]
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.5.jar:na]
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.5.jar:na]
  at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.5.jar:na]
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.5.jar:na]
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.5.jar:na]
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.5.jar:na]
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.5.jar:na]
Caused by: java.lang.NoSuchMethodError: scalikejdbc.DataSourceConnectionPool.<init>(Ljavax/sql/DataSource;)V
  at scalikejdbc.PlayDBPluginAdapter$$anonfun$onStart$1.apply(PlayDBPluginAdapter.scala:42) ~[scalikejdbc-play-dbplugin-adapter_2.11-2.3.5.jar:2.3.5]
  at scalikejdbc.PlayDBPluginAdapter$$anonfun$onStart$1.apply(PlayDBPluginAdapter.scala:40) ~[scalikejdbc-play-dbplugin-adapter_2.11-2.3.5.jar:2.3.5]
  at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.5.jar:na]
  at scalikejdbc.PlayDBPluginAdapter.onStart(PlayDBPluginAdapter.scala:40) ~[scalikejdbc-play-dbplugin-adapter_2.11-2.3.5.jar:2.3.5]
  at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
  at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.5.jar:na]
  at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.8.jar:2.3.8]
  at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.8.jar:2.3.8]
  ... 14 common frames omitted
```

I have tried ScalikeJDBC 2.2.3, which is working well without this problem.
It looks like binary compatibility is lost.

Cause is this commit?

https://github.com/scalikejdbc/scalikejdbc/commit/fc311812292c12622c676ea9d8c351f5290263e4#diff-9295092f40d27c96a155ec490e9cd1a8R24

**Comment by xuwei-k** [comment]
> I have tried ScalikeJDBC 2.2.3, which is working well without this problem.
It looks like binary compatibility is lost.

You are probably right. scalikejdbc does not support perfectly binary compatibility between minor version changes.

scalikejdbc-play-support 2.3.5 depends on scalikejdbc 2.2.0.
https://github.com/scalikejdbc/scalikejdbc-play-support/blob/2.3.5/project/Build.scala#L5

I think we should release new version of scalikejdbc-play-support.

**Comment by seratch** [comment]
Thanks and sorry for bothering you. I'll release new version soon.

**Comment by xuwei-k** [comment]
there is an another solution https://github.com/xuwei-k/scalikejdbc/commit/6453562823f639ec7a8b7b17474093c9e09ce866

**Comment by tsuyoshizawa** [comment]
Thanks for quick response!

**Comment by seratch** [comment]
As @xuwei-k suggested, I think it's better to release fixed scalikejdbc 2.2.5 immediately.

**Comment by seratch** [comment]
Since we found fixing bin compatibility is not an easy work, we'll release scalikejdbc-play-support 2.3.6 with scalikejdbc 2.2.4.

**Comment by seratch** [comment]
2.3.6 is out.
